name: Ultralesson Web Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: build

  #web_test:
   # runs-on: ubuntu-latest
   # strategy:
    #  matrix:
     #   browser: [chrome, firefox, safari]
    #needs: build
    #steps:
     # - uses: actions/checkout@v2
      #- name: Set up JDK 11
       # uses: actions/setup-java@v2
        #with:
        #  java-version: '11'
         # distribution: 'adopt'
          #cache: gradle

      #- name: Run Web Tests in ${{ matrix.browser }}
        #uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
       # with:
        #  arguments: runWebTests -Dbrowser.name=${{ matrix.browser }} -Dbrowser.headless=true

  responsive_view:
   runs-on: ubuntu-latest
   needs: build
   steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run mobile enumeration
      run: npx mobile-enumeration
