name: Ultralesson Web Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: build

  web_test:
    runs-on: ubuntu-latest
    strategy:
     matrix:
      browser: [chromeResponsiveView]
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Run Web Tests in Chrome if [[ "${{ matrix.browser }}" == "chromeResponsiveView" ]]; then
      run: |
        # Install Chrome
        sudo apt update
        sudo apt install -y chromium-browser

        # Run Chrome with mobile emulation using custom user agent and screen size
        chromium-browser --no-sandbox --disable-setuid-sandbox \
          --disable-software-rasterizer --disable-gpu --headless \
          --window-size=360,640 --device-scale-factor=2 \
          --user-agent="Mozilla/5.0 (Linux; Android 10; SM-G970F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Mobile Safari/537.36" \
          https://your-app-url.com
