name: Ultralesson Web Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: build

  #web_test:
   # runs-on: ubuntu-latest
   # strategy:
    #  matrix:
     #   browser: [chrome, firefox, safari]
    #needs: build
    #steps:
     # - uses: actions/checkout@v2
      #- name: Set up JDK 11
       # uses: actions/setup-java@v2
        #with:
        #  java-version: '11'
         # distribution: 'adopt'
          #cache: gradle

      #- name: Run Web Tests in ${{ matrix.browser }}
        #uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
       # with:
        #  arguments: runWebTests -Dbrowser.name=${{ matrix.browser }} -Dbrowser.headless=true
  
  responsive_view:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    
    - name: Install Puppeteer
      run: npm install puppeteer
      
    - name: Run Chrome with responsive design mode
      run: |
        export CHROME_WINDOW_SIZE=1280,800
        export CHROME_DEVICE_SCALE_FACTOR=1
        export CHROME_ARGS="--disable-infobars --disable-web-security --disable-extensions --disable-translate"
        npx puppeteer --no-sandbox --disable-setuid-sandbox --window-size="$CHROME_WINDOW_SIZE" --device-scale-factor="$CHROME_DEVICE_SCALE_FACTOR" "$CHROME_ARGS" -e 'await require("puppeteer").launch({headless:true}).then(async browser => {const page = await browser.newPage(); await page.emulate("iPhone 6/7/8"); await page.goto("https://example.com"); await browser.close();});'
I

