name: Ultralesson Web Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: build
  web_test:
    strategy:
      matrix:
        os: [ubuntu-latest,ubuntu-latest]
        version: [10, 12, 14]
        browsers: [chrome-latest,chrome-latest]
    runs-on: ${{ matrix.os }}
    needs: build
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: setup 
        uses: browser-actions/setup-${{ matrix.version }}
      - name: Run Web Tests
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: runWebTests -Dbrowser.headless=true
      - name: Upload API Artifacts
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: web_test
          path: build/web-reports
